### ISSUE TITLE
This module does not depend on mbed-client

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/mbed-client-mbed-tls#24]
This module does not specify dependency for mbed-client module.
Unable to check compatible versions therefore.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-531

**Comment by yogpan01** [comment]
This module is not dependent on mbed-client. In fact, mbed-client is dependent on this module that's why it doesn't define any mbed-client dependency

**Comment by SeppoTakalo** [comment]
In the source code, you include headers from mbed-client:
~~~
#include "mbed-client/m2mconnectionhandler.h"
#include "mbed-client/m2mconnectionsecurity.h"
~~~

**Comment by SeppoTakalo** [comment]
~~~
[74/93] Building CXX object source/CMakeFiles/mbed-client-mbedtls.dir/home/st/src/mbed-client-mbed-tls/source/m2mconnectionsecurity.cpp.o
FAILED: /usr/bin/c++    -O2 -g -DNDEBUG -I/home/st/src/mbed-client-mbed-tls -I/home/st/src/mbed-client-mbed-tls/yotta_modules/mbedtls -I/home/st/src/mbed-client-mbed-tls/source    -include "/home/st/src/mbed-client-mbed-tls/build/x86-linux-native/yotta_config.h" -MMD -MT source/CMakeFiles/mbed-client-mbedtls.dir/home/st/src/mbed-client-mbed-tls/source/m2mconnectionsecurity.cpp.o -MF "source/CMakeFiles/mbed-client-mbedtls.dir/home/st/src/mbed-client-mbed-tls/source/m2mconnectionsecurity.cpp.o.d" -o source/CMakeFiles/mbed-client-mbedtls.dir/home/st/src/mbed-client-mbed-tls/source/m2mconnectionsecurity.cpp.o -c /home/st/src/mbed-client-mbed-tls/source/m2mconnectionsecurity.cpp
/home/st/src/mbed-client-mbed-tls/source/m2mconnectionsecurity.cpp:18:46: fatal error: mbed-client/m2mconnectionhandler.h: No such file or directory
 #include "mbed-client/m2mconnectionhandler.h"
                                              ^
compilation terminated.
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed
~~~

So you should not implicitly expect that those headers exist in the build environment. You need to specify your dependencies explicitly. Otherwise, I don't think Yotta can check which version of mbed-client this is compatible with.

**Comment by yogpan01** [comment]
Not sure what are you trying to build here. Because mbed-client-mbed-tls is not a standalone component but an extension of mbed-client. It cannot be built standalone. If that's the case you are trying.

**Comment by SeppoTakalo** [comment]
No that is not the point. Reason for the bugreport is that we discussed with Antti about how the dependencies should be instructed on modules, so he pointed me here.
And I think every module should be buildable from their root folder, is a sanity check that you have specified expicitly your modules. Output is just a library that is not usable by itself.
Extensions should not be exceptions. This is just implementing the API specified in headers of mbed-client and therefore you need to be able to specify the API version as a dependency.
