### ISSUE TITLE
Timer timeouts are incorrectly reported as NetworkError in mbed-client

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-mbed-tls#34]
Currently, when a timeout occurs, M2MConnectionSecurityPimpl::timer_expired() has this code:
```
        if(_ssl.p_bio) {
            M2MConnectionHandler* ptr = (M2MConnectionHandler*)_ssl.p_bio;
            ptr->handle_connection_error(4);
         }
```

handle_connection_error() translates to a call to _observer.socket_error(4), which calls M2MInterfaceImpl::socket_error() in mbed-client:
```
      void M2MInterfaceImpl::socket_error(uint8_t error_code)
      {
        tr_debug("M2MInterfaceImpl::socket_error code [%d]", error_code);
        internal_event(STATE_IDLE);
        M2MInterface::Error error = M2MInterface::NetworkError;
        _observer.error(error);
      }
```

The net effect is that every timeout is reported as a NetworkError as opposed to a Timeout to an M2MInterfaceObserver, even in cases when the timeout is benign.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-672

**Comment by anttiylitokola** [comment]
Hi and thanks for you feedback. 

We are currently implementing better connection handling and part of that we will also introduce more precise error codes. We will get back to you once the implementation is done.

Thanks,
Antti

**Comment by anttiylitokola** [comment]
This is now fixed in following PR:
https://github.com/ARMmbed/mbed-client-mbed-tls/pull/38

Application is now informed with error code SecureConnectionFailed if something goes wrong in handshake phase.
