### ISSUE TITLE
M2MConnectionSecurityPimpl uses PRNG

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client-mbed-tls#35]
M2MConnectionSecurityPimpl uses PRNG seeded with RTC for security in  https://github.com/ARMmbed/mbed-client-mbed-tls/blob/master/source/m2mconnectionsecuritypimpl.cpp#L390 .

Independent of that using a PRNG seeded with a time value which can be guessed, is a bad idea. Some platforms do not have RTC. Then this would not give any security at all.

**Comment by markus-becker-tridonic-com** [comment]
@mlnx

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-675

**Comment by yogpan01** [comment]
@markus-becker-tridonic-com Let me check if I understood your requirement correctly, you are proposing that mbed-client-mbedtls component can expose a way to pass the random value into the function, right ? So, we can give something like 
long int get_random_number(); and application can implement it based on their requirement (and of course HW dependent implementation).
Is this what can fix this issue ?

**Comment by markus-becker-tridonic-com** [comment]
Yes. Next to having an interface for Pseudo-RNG numbers, e.g. for non-crypto (e.g. CoAP message IDs), there should be an interface for True-RNG numbers. Actually, there already is an interface, compare https://github.com/ARMmbed/mbedtls/issues/453 and https://github.com/ARMmbed/mbed-client-example-6lowpan/issues/66. However, the RNG handling of the various stack parts needs to be aligned.

**Comment by yogpan01** [comment]
@markus-becker-tridonic-com @mlnx Sorry for the delayed response, I missed your reply. 
We are planning to add API like
long int get_random_number();
Where application can provide their implementation. We will give reference implementation for K64F example and for Linux example.
Hopefully that will provide solution for this issue.

**Comment by markus-becker-tridonic-com** [comment]
Perfect, will close issue, once that is available.

**Comment by yogpan01** [comment]
@markus-becker-tridonic-com : There is now a new API added in mbed-client where application can pass the random number generator function which will be used by mbed-client-mbedtls module.
We have tried to maintain the backward compatibility for the API so in case application doesn't pass this callback, mbed-client continues using the existing mechanism. We will publish the official documentation soon, in the meantime, you can check this PR to see the usage https://github.com/ARMmbed/mbed-client/pull/223/files
We have also introduced another API where application can pass their own implementation for adding entropy source which was requested here https://github.com/ARMmbed/mbed-client-mbed-tls/issues/23
